#ifndef MENUSTATUS_H_INCLUDED
#define MENUSTATUS_H_INCLUDED

enum MenuStates{
    MS_CREATE_MAIN_MENU,
    MS_MAIN_MENU,
    MS_CREATE_SETTINGS_MENU,
    MS_SETTINGS_MENU
};

#endif // MENUSTATUS_H_INCLUDED
