#ifndef MULTIPLAYERSTATES_H_INCLUDED
#define MULTIPLAYERSTATES_H_INCLUDED


enum MultiplayerStates
{
    MPS_SELECT_MODE,
    MPS_ENTER_IP,
    MPS_LOAD_ENTER_IP,
    MPS_LOBBY,
    MPS_LOAD_LOBBY
};

#endif // MULTIPLAYERSTATES_H_INCLUDED