#ifndef MULTIPLAYERMENUSTATES_H
#define MULTIPLAYERMENUSTATES_H


enum MultiplayerMenuStates
{
    MPMS_SELECT_MODE,
    MPMS_ENTER_IP,
    MPMS_LOAD_ENTER_IP,
    MPMS_LOBBY,
    MPMS_LOAD_LOBBY
};

#endif // MULTIPLAYERMENUSTATES_H
