#ifndef MULTIPLAYERMENUSTATES_H
#define MULTIPLAYERMENUSTATES_H


enum MultiplayerMenuStates
{
    MPS_SELECT_MODE,
    MPS_ENTER_IP,
    MPS_LOAD_ENTER_IP,
    MPS_LOBBY,
    MPS_LOAD_LOBBY
};

#endif // MULTIPLAYERMENUSTATES_H