#ifndef MULTIPLAYERSTATES_H
#define MULTIPLAYERSTATES_H

enum MultiplayerStates
{
    MPS_MENU_CONNECTING,
    MPS_MENU_WAITING,
    MPS_START_GAME,
    MPS_PLAY,
    MPS_PAUSE_MENU,
    MPS_GAME_OVER
};

#endif // MULTIPLAYERSTATES_H
